name: MohiMine
main: kr.mohi.mohimine.MohiMine
author: "MohiPE(물외한인)"
version: "1.0.0"
api: ["1.0.0"]
permissions:
 mohimine.command.*:
  default: OP
  children:
   mohimine.command.pos:
    default: OP
   mohimine.command.set:
    default: OP
   mohimine.command.del:
    default: OP
 mohimine.mining:
  default: true